# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

annotate_by_mass <- function(peaks, adducts, compounds, tolerance) {
    .Call(`_xmsannotator_annotate_by_mass`, peaks, adducts, compounds, tolerance)
}

