# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

annotate_by_mass <- function(peak_table, adduct_table, compound_table, tolerance) {
    .Call(`_xmsannotator_annotate_by_mass`, peak_table, adduct_table, compound_table, tolerance)
}

